name: hackthon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  animated_switcher_plus: ^1.4.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/lang/
    - assets/fonts/Intel/
    - assets/fonts/Tajawal/
  fonts:
        - family: Intel
          fonts:
            - asset: "assets/fonts/Intel/Intel Clear WArabic Regular.ttf"
            - asset: "assets/fonts/Intel/Intel Clear WArabic Light .ttf"
            - asset: "assets/fonts/Intel/Intel Clear WArabic Bold.ttf"
        - family: Tajawal
          fonts:
            - asset: "assets/fonts/Tajawal/Tajawal-Bold.ttf"
            - asset: "assets/fonts/Tajawal/Tajawal-Light.ttf"
            - asset: "assets/fonts/Tajawal/Tajawal-Regular.ttf"


